spring.application.name=notification-backend

server.port=${PORT:8090}

spring.datasource.url=jdbc:mysql://localhost:3306/college_db
spring.datasource.username=root
spring.datasource.password=Dev@MySql7663

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true