name: Notify Cron Job

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  call-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger API
        run: |
          curl -X GET "https://notify-x8o4.onrender.com/api/send-notification"
